### ISSUE TITLE
Adding ability to subscribe for onConnected event

### ISSUE THREAD

**Issue by andkulikov** [florent37/Wear-Emmet#3]
Hello! Thanks for useful library!

Why are waitingItems exists only for datamaps? I just want to send simple message to wear from smartphone right after onConnected will be called.
Also i think it will be useful to be able adding listener to Emmet for events onConnected and onConnectionFailed. With this it will be able to solve first problem with putting sendMessage call in onConnected callback.

And i can help you with this functionality if you want or if you haven't free time for this.

**Comment by florent37** [comment]
it's just a forget, It would be nice to add a list with waitings messages yes.
And why not a listener/callback to be informed witch events onConnected & onConnectionFailed

Yes, you can help me if you want, it would be super cool :+1:

**Comment by andkulikov** [comment]
fix already merged. thanks)
