### ISSUE TITLE
Question, not an issue. Does it use proto buffers?

### ISSUE THREAD

**Issue by greenspand** [florent37/Wear-Emmet#4]

**Comment by florent37** [comment]
No it's an abstraction of Google Message API & Google Data API

**Comment by greenspand** [comment]
Ok, so that means the Google Data and Message API works 100% only that the implementation details, boilerplate has gone down now right?

**Comment by florent37** [comment]
Yes Google Data & Message API works fine, I used to implement them manually in my Wear Application.
I just made a simple abstraction to simplify usage & accelerate develpment

**Comment by florent37** [comment]
I tried to reproduce the concept of Retrofit, abstract the HTTP calls method calls on interface

**Comment by greenspand** [comment]
Awesome, thx for the info.
