### ISSUE TITLE
Logs should be disabled by default

### ISSUE THREAD

**Issue by andkulikov** [florent37/Wear-Emmet#8]
I think it will be better to disable all logs in library by default and enable it only for debugging purposes while development

**Comment by florent37** [comment]
thanks, I added it in the new version, I'll just test it and push the new version to jcenter, thanks again for helping me, I appreciate it :+1: :smiley:

**Comment by andkulikov** [comment]
hello!) any estimates for new version release date?

**Comment by florent37** [comment]
Yes, I already published ^^

1.0.1

**Comment by andkulikov** [comment]
but as far as i can see 1.0.1 version from maven doesn't contain these changes

https://bintray.com/florent37/maven/Emmet/1.0.1/view
Version Publication Date
Updated May 04, 2015

maybe your previous release also have version 1.0.1 and you need to increment it?

**Comment by florent37** [comment]
Oh yes, was my fault.
Thanks for noticed my ;)

can you check now ?

2015-05-09 0:12 GMT+02:00 Andrey Kulikov notifications@github.com:

**Comment by andkulikov** [comment]
with 1.0.2 it is going to be ok. thanks)

**Comment by florent37** [comment]
thanks to you :)

2015-05-09 0:22 GMT+02:00 Andrey Kulikov notifications@github.com:
